version : '3'

services:
    distro:
        image: alpine
        restart: always
        container_name: custom_alpine
        entrypoint: tail -f /dev/null

    database:
        image: postgres:latest
        container_name: postgres_db
        restart: always
        ports:
            - "5432:5432"
        environment: 
            POSTGRES_HOST_AUTH_METHOD: trust
        volumes:
            - ../dump:/tmp/
    
    web:
        image: nginx
        restart: always
        container_name: nginx_web
        ports:
            - "8080:80"
        volumes:
            - ./mysite.template:/etc/nginx/conf.d/mysite.template
        environment:
            - NGINX_HOST=sample.container_name
            - NGINX_PORT=80
        links:
            database:database
            distro

volumes:
    data:
        external: true
